version: "3.9"

networks:
  memelandia-net:
    name: memelandia-net
    driver: bridge

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    networks:
      - memelandia-net
    ports:
      - "9411:9411"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9411/health"]
      interval: 5s
      timeout: 3s
      retries: 25
    restart: unless-stopped

  config-server:
    build: ./config-server
    container_name: config-server
    networks:
      - memelandia-net
    ports:
      - "8888:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1s
      timeout: 3s
      retries: 25
    restart: unless-stopped

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    networks:
      - memelandia-net
    ports:
      - "9091:8080"
    depends_on:
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1s
      timeout: 3s
      retries: 25
    restart: unless-stopped

  gateway:
    build: ./gateway
    container_name: gateway
    networks:
      - memelandia-net
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8080/eureka
      MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1s
      timeout: 3s
      retries: 25
    restart: unless-stopped

  user-service:
    build: ./user-service
    container_name: user-service
    networks:
      - memelandia-net
    depends_on:
      discovery-server:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8080/eureka
      MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
      MONGO_URI: mongodb://user_service:user_1234321@user-db:27017
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1s
      timeout: 3s
      retries: 25
    restart: unless-stopped

  category-service:
    build: ./category-service
    container_name: category-service
    networks:
      - memelandia-net
    depends_on:
      discovery-server:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8080/eureka
      MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
      MONGO_URI: mongodb://category_service:category_1234321@category-db:27017
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1s
      timeout: 3s
      retries: 25
    restart: unless-stopped

  meme-service:
    build: ./meme-service
    container_name: meme-service
    networks:
      - memelandia-net
    depends_on:
      discovery-server:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8080/eureka
      MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
      MONGO_URI: mongodb://meme_service:meme_1234321@meme-db:27017
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1s
      timeout: 3s
      retries: 25
    restart: unless-stopped
