version: "3.9"

networks:
  memelandia-net:
    name: memelandia-net
    driver: bridge

services:
  user-mongo:
    image: mongo:8.2
    container_name: user-db
    ports:
      - "27020:27017"
    volumes:
      - user_db_data:/data/db
    networks:
      - memelandia-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_service
      MONGO_INITDB_ROOT_PASSWORD: user_1234321

  category-mongo:
    image: mongo:8.2
    container_name: category-db
    ports:
      - "27021:27017"
    volumes:
      - category_db_data:/data/db
    networks:
      - memelandia-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: category_service
      MONGO_INITDB_ROOT_PASSWORD: category_1234321

  meme-mongo:
    image: mongo:8.2
    container_name: meme-db
    ports:
      - "27022:27017"
    volumes:
      - meme_db_data:/data/db
    networks:
      - memelandia-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: meme_service
      MONGO_INITDB_ROOT_PASSWORD: meme_1234321

volumes:
  user_db_data:
  category_db_data:
  meme_db_data:
