version: "3.9"

networks:
  memelandia-net:
    name: memelandia-net
    external: true

services:
  config-server:
    build: ./config-server
    container_name: config-server
    networks:
      - memelandia-net
    ports:
      - "8888:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    networks:
      - memelandia-net
    ports:
      - "9091:8080"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  gateway:
    build: ./gateway
    container_name: gateway
    networks:
      - memelandia-net
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8080/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  user-service:
    build: ./user-service
    container_name: user-service
    networks:
      - memelandia-net
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8080/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  category-service:
    build: ./category-service
    container_name: category-service
    networks:
      - memelandia-net
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8080/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  meme-service:
    build: ./meme-service
    container_name: meme-service
    networks:
      - memelandia-net
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8080/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1s
      timeout: 3s
      retries: 10
    restart: unless-stopped
