server:
  port: 8092

spring:
  application:
    name: category-service
  # data:
  #   mongodb:
  #     uri: http://localhost:27020/teste

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka

springdoc:
  swagger-ui:
    enabled: false
